# Generated by Django 5.2.17 on 2026-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_installment_id_alter_member_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
            ],
            options={
                'ordering': ['start_month', 'end_month'],
                'constraints': [models.UniqueConstraint(fields=('start_month', 'end_month'), name='unique_collection_period')],
            },
        ),
    ]
